### ISSUE TITLE
Player can re-join when kicked from clan

### ISSUE THREAD

**Issue by Tracker6310** [bitquest/bitquest#126] opened 2017-01-25 22:58 UTC
When a player accepts invite to join a clan, invite is not deleted. 
If player is kicked from clan at some point, invite is still in redis, allowing them to rejoin at any time

**Comment by CubeFromSpace** [comment] 2017-01-26 01:02
Wait... clans are working?

**Comment by theraccoonbear** [comment] 2017-01-26 02:20
@CubeFromSpace I've not been on for some time, but I believe clans have been in place on beta for some time.  I've seen it discussed on Slack.

**Comment by CubeFromSpace** [comment] 2017-01-31 17:23
Isn't there a way to delete the REDIS info from the plugin? Maybe that will help

**Comment by juanj** [comment] 2017-03-19 23:10
This issue can be close.
The problem is fixed in #130

**Comment by CubeFromSpace** [comment] 2017-03-23 16:11
@explodi /\
                 |

**Comment by CubeFromSpace** [comment] 2017-03-23 16:11
Oops

**Closed** 2017-04-25 15:07 UTC
